CREATE TABLE IF NOT EXISTS CUSTOMER(
NAME TEXT,
COUNTRY TEXT,
PRODUCTS TEXT,
PRICE INTEGER
);

INSERT INTO CUSTOMER(NAME, COUNTRY, PRODUCTS, PRICE)
VALUES
('AETER','CALIFORNIA','SOFA', 45000),
('AONGOR','FLORIDA','WASHING MACHINE', 50000),
('POCHA','FLORIDA','SOFA', 43000),
('LIGHTHOR','NEW YORK','TABLE', 3900),
('MINCA','DOWNTOWN','CHAIR', 4600),
('AREA','CHINA','WASINHG MACHINE', 51000);

SELECT *
FROM CUSTOMER
WHERE NAME LIKE "_%OR";

SELECT *
FROM CUSTOMER
WHERE NAME LIKE "A%";

SELECT DISTINCT NAME
FROM CUSTOMER
WHERE PRICE >= 5000;

SELECT *
FROM CUSTOMER
ORDER BY PRICE DESC;

SELECT DISTINCT COUNTRY
FROM CUSTOMER;